import { ModelOption, FeatureCategory } from '../types';

export const DEFAULT_MODELS: Record<FeatureCategory, ModelOption[]> = {
  chat: [
    {
      id: 'google/gemini-3.8-flash',
      name: 'Gemini 3.8 Flash (OpenRouter) - ئاساسلىق تەۋسىيە',
      provider: 'openrouter',
      category: ['chat', 'translate'],
      description: 'Google ئەڭ يېڭى يۇقىرى سۈرئەتلىك ۋە كۈچلۈك كۆپ ئىقتىدارلىق فلاجىمان مودېلى',
      recommended: true,
    },
    {
      id: 'gemini-direct:gemini-3.8-flash',
      name: 'Gemini 3.8 Flash (Direct Google API)',
      provider: 'gemini',
      category: ['chat', 'translate'],
      description: 'Google Gemini API ئاچقۇچى بىلەن بىۋاسىتە ئۇلىنىش',
      recommended: true,
    },
    {
      id: 'google/gemini-2.5-pro',
      name: 'Gemini 2.5 Pro (OpenRouter)',
      provider: 'openrouter',
      category: ['chat', 'translate'],
      description: 'Top-tier complex reasoning and multilingual proficiency',
    },
    {
      id: 'anthropic/claude-3.5-sonnet',
      name: 'Claude 3.5 Sonnet (OpenRouter)',
      provider: 'openrouter',
      category: ['chat'],
      description: 'High standard intelligence and natural conversations',
    },
    {
      id: 'openai/gpt-4o',
      name: 'GPT-4o (OpenRouter)',
      provider: 'openrouter',
      category: ['chat', 'translate'],
      description: 'OpenAI versatile multimodal flagship',
    },
  ],
  translate: [
    {
      id: 'google/gemini-3.8-flash',
      name: 'Gemini 3.8 Flash (OpenRouter) - ئاساسلىق تەۋسىيە',
      provider: 'openrouter',
      category: ['translate'],
      description: 'ئۇيغۇرچە، ئىنگىلىزچە، تۈركچە ۋە ئەرەبچە تىللىرى ئۈچۈن نۇقسانسىز ئەڭ يېڭى تەرجىمە مودېلى',
      recommended: true,
    },
    {
      id: 'gemini-direct:gemini-3.8-flash',
      name: 'Gemini 3.8 Flash (Direct Google API)',
      provider: 'gemini',
      category: ['translate'],
      description: 'Direct Google API key translation',
      recommended: true,
    },
    {
      id: 'google/gemini-2.5-pro',
      name: 'Gemini 2.5 Pro (OpenRouter)',
      provider: 'openrouter',
      category: ['translate'],
      description: 'Deepest contextual nuance and cultural style handling',
    },
    {
      id: 'anthropic/claude-3.5-sonnet',
      name: 'Claude 3.5 Sonnet (OpenRouter)',
      provider: 'openrouter',
      category: ['translate'],
      description: 'Fluid literary and workplace style translations',
    },
  ],
  image: [
    {
      id: 'google/gemini-3.8-flash',
      name: 'Gemini 3.8 Flash (OpenRouter Multimodal Imaging) - تەۋسىيە',
      provider: 'openrouter',
      category: ['image'],
      description: 'Gemini 3.8 Flash كۆپ ئىقتىدارلىق كۆرۈنۈش ۋە سەنئەت ھاسىللاش ماتورى',
      recommended: true,
    },
    {
      id: 'black-forest-labs/flux-1-schnell',
      name: 'FLUX.1 Schnell (OpenRouter) - فوتو سۈپەت',
      provider: 'openrouter',
      category: ['image'],
      description: 'High-speed, photorealistic imagery with great detail',
      recommended: true,
    },
    {
      id: 'black-forest-labs/flux-1-dev',
      name: 'FLUX.1 Dev (OpenRouter)',
      provider: 'openrouter',
      category: ['image'],
      description: 'Top-tier image detail, lighting, and composition quality',
    },
    {
      id: 'google/imagen-3.0-generate-002',
      name: 'Google Imagen 3 (OpenRouter / Direct)',
      provider: 'openrouter',
      category: ['image'],
      description: 'Google state-of-the-art photorealistic image generation',
    },
  ],
  tts: [
    {
      id: 'google/gemini-3.8-flash',
      name: 'Gemini 3.8 Flash Audio & Voice (OpenRouter) - تەۋسىيە',
      provider: 'openrouter',
      category: ['tts'],
      description: 'Gemini 3.8 Flash ئاۋاز تەلەپپۇز ئىنچىكىلىكى ۋە نۇتۇق پىششىقلاش',
      recommended: true,
    },
    {
      id: 'gemini-direct:gemini-3.8-flash',
      name: 'Gemini 3.8 Flash Direct Audio (Google)',
      provider: 'gemini',
      category: ['tts'],
      description: 'Direct Google Gemini Audio API',
    },
    {
      id: 'browser-native:ug-multilingual',
      name: 'Native Browser Multilingual Speech (ئەڭ تېز / بارلىق قۇرۇلما)',
      provider: 'gemini',
      category: ['tts'],
      description: 'Built-in audio synthesizer with zero latency',
    },
  ],
  video: [
    {
      id: 'google/gemini-3.8-flash',
      name: 'Gemini 3.8 Flash Commercial Director (OpenRouter) - تەۋسىيە',
      provider: 'openrouter',
      category: ['video'],
      description: 'Gemini 3.8 Flash مەھسۇلات ئىلانى سېنارىيەسى ۋە كۆرۈنۈش لايىھەسى',
      recommended: true,
    },
    {
      id: 'google/veo-2.0-generate-001',
      name: 'Google Veo 2.0 (Video Generation)',
      provider: 'openrouter',
      category: ['video'],
      description: 'High-definition cinematic video model',
    },
  ],
  ocr: [
    {
      id: 'google/gemini-3.8-flash',
      name: 'Gemini 3.8 Flash Vision (OpenRouter) - تەۋسىيە',
      provider: 'openrouter',
      category: ['ocr'],
      description: 'ئۇيغۇرچە ۋە كۆپ تىللىق رەسىم، پۈتۈك، كىتاب يۈزىدىكى تېكىستلەرنى 99% ئېنىقلىقتا بايقاش',
      recommended: true,
    },
    {
      id: 'gemini-direct:gemini-3.8-flash',
      name: 'Gemini 3.8 Flash Direct Vision (Google)',
      provider: 'gemini',
      category: ['ocr'],
      description: 'Direct Google Gemini Multimodal Vision API',
    },
    {
      id: 'openai/gpt-4o',
      name: 'GPT-4o Vision (OpenRouter)',
      provider: 'openrouter',
      category: ['ocr'],
      description: 'OpenAI multi-turn multimodal document reader',
    },
  ],
  writer: [
    {
      id: 'google/gemini-3.8-flash',
      name: 'Gemini 3.8 Flash Writer (OpenRouter) - تەۋسىيە',
      provider: 'openrouter',
      category: ['writer'],
      description: 'ئۇيغۇرچە ئىملا تۈزىتىش، ماقالە يېزىش، سېتىش تېكىستى ۋە ئەدەبىي ئۇسلۇب كۈچەيتكۈچى',
      recommended: true,
    },
    {
      id: 'anthropic/claude-3.5-sonnet',
      name: 'Claude 3.5 Sonnet (OpenRouter)',
      provider: 'openrouter',
      category: ['writer'],
      description: 'ئەڭ گۈزەل تەبىئىي بايان ۋە ئىجادىي يېزىقچىلىق پېشۋاسى',
    },
    {
      id: 'google/gemini-2.5-pro',
      name: 'Gemini 2.5 Pro (OpenRouter)',
      provider: 'openrouter',
      category: ['writer'],
      description: 'چوڭقۇر ئىلمىي ۋە تەتقىقات يېزىقچىلىقى',
    },
  ],
  stt: [
    {
      id: 'google/gemini-3.8-flash',
      name: 'Gemini 3.8 Flash Speech Recognizer (OpenRouter) - تەۋسىيە',
      provider: 'openrouter',
      category: ['stt'],
      description: 'ئاۋازنى ئاڭلاپ نۇقسانسىز ئۇيغۇرچە ۋە كۆپ تىللىق تېكىستكە ئايلاندۇرۇش',
      recommended: true,
    },
    {
      id: 'browser-native:ug-speech-recognition',
      name: 'Native Browser Speech Recognition',
      provider: 'gemini',
      category: ['stt'],
      description: 'تور كۆرگۈچ مىكروفونى بىلەن بىر ۋاقىتلىق ئاۋاز بايقاش',
    },
  ],
  marketing: [
    {
      id: 'google/gemini-3.8-flash',
      name: 'Gemini 3.8 Flash Marketing Expert (OpenRouter) - تەۋسىيە',
      provider: 'openrouter',
      category: ['marketing'],
      description: 'TikTok / Instagram / تور دۇكانلىرى ئۈچۈن خېرىدارنى قايىل قىلىدىغان ئىلان سۆزلىرى ۋە ۋىرۇسلۇق تېما',
      recommended: true,
    },
    {
      id: 'openai/gpt-4o',
      name: 'GPT-4o Copywriter (OpenRouter)',
      provider: 'openrouter',
      category: ['marketing'],
      description: 'Creative marketing slogans and social media strategies',
    },
  ],
};

export const DEFAULT_SELECTED_MODELS: Record<FeatureCategory, string> = {
  chat: 'google/gemini-3.8-flash',
  translate: 'google/gemini-3.8-flash',
  image: 'google/gemini-3.8-flash',
  tts: 'google/gemini-3.8-flash',
  video: 'google/gemini-3.8-flash',
  ocr: 'google/gemini-3.8-flash',
  writer: 'google/gemini-3.8-flash',
  stt: 'google/gemini-3.8-flash',
  marketing: 'google/gemini-3.8-flash',
};
